#!/usr/bin/env bash
# engineering-craft / dev-pipeline / spec-forge — fresh-machine bootstrap
#
# What this does (in order):
#   1. Verifies prerequisites (git, jq, optional: gh, openssl, python3)
#   2. Clones engineering-craft (if not already from this script's location)
#   3. Clones dev-pipeline plugin to ~/.claude/plugins/marketplaces/local/plugins/dev-pipeline
#   4. Clones spec-forge to ~/Desktop/projects/spec-forge (or $SPEC_FORGE_DIR)
#   5. Installs engineering-craft hooks at ~/.claude/hooks/
#   6. Merges hook registrations into ~/.claude/settings.json
#   7. Installs the launchd consolidation reminder
#   8. Optionally re-installs git hooks for the current project
#
# Idempotent — safe to re-run. Skips steps that are already done.
#
# Usage:
#   bash bootstrap/install.sh                    # default: all the above
#   SKIP_DEV_PIPELINE=1 bash bootstrap/install.sh  # don't clone dev-pipeline
#   SKIP_SPEC_FORGE=1   bash bootstrap/install.sh  # don't clone spec-forge
#   SPEC_FORGE_DIR=~/code/spec-forge bash bootstrap/install.sh
#
# Source repos (override via env if you fork):
#   ENGINEERING_CRAFT_REPO  default: https://github.com/orocsy/engineering-craft
#   DEV_PIPELINE_REPO       default: git@github.com:orocsy/dev-pipeline.git
#   SPEC_FORGE_REPO         default: git@github.com:orocsy/spec-forge.git

set -euo pipefail

ENGINEERING_CRAFT_REPO="${ENGINEERING_CRAFT_REPO:-https://github.com/orocsy/engineering-craft}"
DEV_PIPELINE_REPO="${DEV_PIPELINE_REPO:-git@github.com:orocsy/dev-pipeline.git}"
SPEC_FORGE_REPO="${SPEC_FORGE_REPO:-git@github.com:orocsy/spec-forge.git}"
SPEC_FORGE_DIR="${SPEC_FORGE_DIR:-$HOME/Desktop/projects/spec-forge}"

CLAUDE_DIR="$HOME/.claude"
SKILL_DIR="$CLAUDE_DIR/skills/engineering-craft"
MIRROR_DIR="$CLAUDE_DIR/external-mirrors/engineering-craft"
PLUGIN_DIR="$CLAUDE_DIR/plugins/marketplaces/local/plugins/dev-pipeline"
HOOK_DIR="$CLAUDE_DIR/hooks"
SETTINGS="$CLAUDE_DIR/settings.json"
LAUNCH_AGENTS="$HOME/Library/LaunchAgents"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

step() { printf "\n\033[1;36m▶ %s\033[0m\n" "$1"; }
ok()   { printf "  \033[32m✓\033[0m %s\n" "$1"; }
warn() { printf "  \033[33m⚠\033[0m %s\n" "$1"; }
err()  { printf "  \033[31m✗\033[0m %s\n" "$1" >&2; }

# ─── 1. Prereqs ──────────────────────────────────────────────────────────────
step "Checking prerequisites"
for tool in git jq; do
  if command -v "$tool" >/dev/null 2>&1; then
    ok "$tool: $(command -v $tool)"
  else
    err "$tool: not found — install before continuing"
    exit 1
  fi
done
for opt in gh openssl python3; do
  if command -v "$opt" >/dev/null 2>&1; then
    ok "$opt (optional): $(command -v $opt)"
  else
    warn "$opt (optional): not found — some features will be limited"
  fi
done

# ─── 2. engineering-craft skill ──────────────────────────────────────────────
step "Installing engineering-craft skill"
mkdir -p "$CLAUDE_DIR/skills" "$CLAUDE_DIR/external-mirrors" "$CLAUDE_DIR/lessons-journal"
if [ -d "$SKILL_DIR/categories" ]; then
  ok "Already present at $SKILL_DIR ($(find "$SKILL_DIR/categories" -name "*.md" -path "*/rules/*" | wc -l | tr -d ' ') rules)"
else
  if [ "$SCRIPT_DIR" = "$SKILL_DIR/bootstrap" ]; then
    ok "Skill is already in place (we are running from inside it)"
  else
    git clone "$ENGINEERING_CRAFT_REPO" "$SKILL_DIR"
    ok "Cloned to $SKILL_DIR"
  fi
fi

# Clone the read-write mirror (used by /dev-pipeline:consolidate-lessons to push)
if [ -d "$MIRROR_DIR/.git" ]; then
  ok "Mirror clone already at $MIRROR_DIR"
else
  git clone "$ENGINEERING_CRAFT_REPO" "$MIRROR_DIR" 2>&1 | tail -2
  ok "Mirror cloned to $MIRROR_DIR (separate from skill, used for consolidation pushes)"
fi

# Write the .public-mirror-config so consolidate-lessons knows where to push
cat > "$SKILL_DIR/.public-mirror-config" <<EOF
# engineering-craft public mirror configuration
# Generated by bootstrap/install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
MIRROR_REPO="$(echo "$ENGINEERING_CRAFT_REPO" | sed -E 's|.*github\.com[:/]||; s|\.git$||')"
MIRROR_BRANCH="main"
MIRROR_DIR="$MIRROR_DIR"
EOF
ok "Mirror config written"

# ─── 3. dev-pipeline plugin ──────────────────────────────────────────────────
if [ -z "${SKIP_DEV_PIPELINE:-}" ]; then
  step "Installing dev-pipeline plugin"
  mkdir -p "$(dirname "$PLUGIN_DIR")"
  if [ -d "$PLUGIN_DIR/.git" ]; then
    ok "Already present at $PLUGIN_DIR"
  else
    if git clone "$DEV_PIPELINE_REPO" "$PLUGIN_DIR" 2>&1 | tail -3; then
      ok "Cloned to $PLUGIN_DIR — Claude Code will auto-discover /dev-pipeline:* commands next session"
    else
      err "Failed to clone dev-pipeline (auth?). Run: git clone $DEV_PIPELINE_REPO $PLUGIN_DIR"
    fi
  fi
fi

# ─── 4. spec-forge ──────────────────────────────────────────────────────────
if [ -z "${SKIP_SPEC_FORGE:-}" ]; then
  step "Installing spec-forge"
  mkdir -p "$(dirname "$SPEC_FORGE_DIR")"
  if [ -d "$SPEC_FORGE_DIR/.git" ]; then
    ok "Already present at $SPEC_FORGE_DIR"
  else
    if git clone "$SPEC_FORGE_REPO" "$SPEC_FORGE_DIR" 2>&1 | tail -3; then
      ok "Cloned to $SPEC_FORGE_DIR — used by /dev-pipeline:scaffold-from-prd"
    else
      err "Failed to clone spec-forge (auth?). Run: git clone $SPEC_FORGE_REPO $SPEC_FORGE_DIR"
    fi
  fi
fi

# ─── 5. Hooks ───────────────────────────────────────────────────────────────
step "Installing hooks"
mkdir -p "$HOOK_DIR"

# 5a. Copy the engineering-craft post-codex-fix hook
if [ -f "$HOOK_DIR/post-codex-fix-extract-lesson.sh" ]; then
  ok "post-codex-fix-extract-lesson.sh: already installed"
else
  cp "$SCRIPT_DIR/hooks/post-codex-fix-extract-lesson.sh" "$HOOK_DIR/"
  chmod +x "$HOOK_DIR/post-codex-fix-extract-lesson.sh"
  ok "post-codex-fix-extract-lesson.sh: installed"
fi

# 5b. Merge engineering-craft fragment into session-start.sh (or create new)
SS="$HOOK_DIR/session-start.sh"
FRAGMENT_MARKER="# === engineering-craft auto-bootstrap"
if [ -f "$SS" ] && grep -q "$FRAGMENT_MARKER" "$SS"; then
  ok "session-start.sh: engineering-craft fragment already present"
elif [ -f "$SS" ]; then
  cat >> "$SS" <<'EOF'

# ============================================================================
# engineering-craft fragment (added by bootstrap/install.sh)
# ============================================================================
EOF
  cat "$SCRIPT_DIR/hooks/session-start-fragment.sh" >> "$SS"
  ok "session-start.sh: appended engineering-craft fragment"
else
  cat > "$SS" <<'EOF'
#!/bin/bash
# SessionStart hook (auto-generated by engineering-craft bootstrap)
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"
cd "$PROJECT_DIR" 2>/dev/null || exit 0

EOF
  cat "$SCRIPT_DIR/hooks/session-start-fragment.sh" >> "$SS"
  echo "exit 0" >> "$SS"
  chmod +x "$SS"
  ok "session-start.sh: created with engineering-craft fragment"
fi

# ─── 6. Settings (hook registrations) ───────────────────────────────────────
step "Updating ~/.claude/settings.json"
if [ ! -f "$SETTINGS" ]; then
  echo '{}' > "$SETTINGS"
  ok "Created empty settings.json"
fi

# Use jq to merge hook registration without clobbering existing keys
TMP_SETTINGS="$(mktemp)"
jq -s '
  .[0] as $current
  | .[1] as $new
  | $current
  | .hooks = ((.hooks // {}) | . as $h | $h
      | .PostToolUse = ((.PostToolUse // []) + ($new.hooks.PostToolUse // []))
      | .SessionStart = ((.SessionStart // []) +
          (if (.SessionStart // []) | any(.hooks[]?.command | contains("session-start.sh")) then []
           else [{"matcher": ".*", "hooks": [{"type": "command", "command": "bash \"$HOME/.claude/hooks/session-start.sh\"", "timeout": 5}]}]
           end))
    )
' "$SETTINGS" "$SCRIPT_DIR/settings/hook-registrations.json" > "$TMP_SETTINGS"

# Dedup PostToolUse Bash matchers (in case re-running install)
jq '
  .hooks.PostToolUse |= (
    group_by(.matcher) | map(
      if length > 1 then
        { matcher: .[0].matcher, hooks: ([.[].hooks[]] | unique_by(.command)) }
      else .[0] end
    )
  )
' "$TMP_SETTINGS" > "$SETTINGS"
rm "$TMP_SETTINGS"
ok "settings.json updated (hooks merged, deduped)"

# ─── 7. launchd consolidation reminder ──────────────────────────────────────
step "Installing launchd consolidation reminder"
mkdir -p "$LAUNCH_AGENTS"
PLIST_NAME="com.engineering-craft.consolidation-reminder.plist"
PLIST_DST="$LAUNCH_AGENTS/$PLIST_NAME"

if [ -f "$PLIST_DST" ]; then
  launchctl unload "$PLIST_DST" 2>/dev/null || true
fi
cp "$SCRIPT_DIR/launchd/$PLIST_NAME" "$PLIST_DST"
launchctl load -w "$PLIST_DST"
ok "launchd job loaded ($(launchctl list | grep engineering-craft | awk '{print $3}'))"
ok "Will fire every 172800s (2 days); writes marker if journal has new entries"

# ─── 8. Project-side git hooks (if in a project) ───────────────────────────
if [ -d ".git" ] && [ -x "$HOME/.claude/setup-git-hooks.sh" ]; then
  step "Installing project git hooks (current project)"
  bash "$HOME/.claude/setup-git-hooks.sh" 2>&1 | tail -3 || true
fi

# ─── Done ───────────────────────────────────────────────────────────────────
step "Done"
cat <<EOF

Engineering-craft + dev-pipeline + spec-forge are installed.

What works now:
  • engineering-craft skill auto-loads in any Claude Code session (43 rules, 14 categories)
  • /dev-pipeline:* commands available next time you start Claude Code
  • SessionStart hook keeps engineering-craft fresh (24h rate-limited)
  • PostToolUse(Bash) hook journals review-fix commits to ~/.claude/lessons-journal/
  • launchd job reminds every 2 days to run /dev-pipeline:consolidate-lessons

Next steps:
  1. Open Claude Code in any project. Verify the session start log shows
     "[session] engineering-craft installed: 43 rules across 14 categories"
     OR no engineering-craft message at all (means it was already there).
  2. For NEW projects: run /dev-pipeline:init — it scaffolds .claude/ structure
     and detects your stack.
  3. To create a project-level CLAUDE.md from the template:
     cp $SCRIPT_DIR/templates/project-CLAUDE.md .claude/CLAUDE.md
     Then fill in the {{PLACEHOLDERS}}.

Verify the loop end-to-end:
  bash ~/.claude/hooks/session-start.sh        # see auto-bootstrap output
  python3 $SKILL_DIR/scripts/lint.py           # see lint pass (should be clean)
  ls ~/.claude/lessons-journal/                # see journal dir
  launchctl list | grep engineering-craft      # see launchd loaded

Re-run safely:
  bash $0  # idempotent
EOF
